// piblockly/media/user_modules/_core_hw_lib/zh-hant.js

export const MSG_PIBLOCKLY_HW_ZH_HANT = {
  // Category Keys
  "PIBLOCKLY_HW_CATEGORY": "硬體",
  "PIBLOCKLY_HW_CATEGORY_SENSORS": "感測器",
  "PIBLOCKLY_HW_CATEGORY_ACTUATORS": "致動器",
  "PIBLOCKLY_HW_CATEGORY_AI": "人工智慧",
  "PIBLOCKLY_HW_CATEGORY_HUSKYLENS": "Huskylens",

  // Ultrasonic Distance Block
  "PIBLOCKLY_HW_ULTRASONIC_DISTANCE_TITLE": "HC-SR04 超音波測距",
  "PIBLOCKLY_HW_ULTRASONIC_DISTANCE_TOOLTIP": "讀取 HC-SR04 超音波感測器距離",
  "PIBLOCKLY_HW_ULTRASONIC_DISTANCE_HELPURL": "https://www.example.com/hcsr04",
  "PIBLOCKLY_HW_ULTRASONIC_DISTANCE_TRIG_PIN": "觸發腳位",
  "PIBLOCKLY_HW_ULTRASONIC_DISTANCE_ECHO_PIN": "回聲腳位",

  // DHT Sensor Block
  "PIBLOCKLY_HW_DHT_READ_TITLE": "讀取 DHT",
  "PIBLOCKLY_HW_DHT_ON_PIN": "於腳位",
  "PIBLOCKLY_HW_DHT_READING": "讀取:",
  "PIBLOCKLY_HW_DHT_READ_TOOLTIP": "從 DHT 感測器讀取溫度或濕度。需要安裝 Adafruit 的 'DHT sensor library' 函式庫。",
  "PIBLOCKLY_HW_DHT_TYPE_11": "DHT11",
  "PIBLOCKLY_HW_DHT_TYPE_22": "DHT22",
  "PIBLOCKLY_HW_DHT_READING_TEMP": "溫度 (°C)",
  "PIBLOCKLY_HW_DHT_READING_HUMIDITY": "濕度 (%)",

  // Huskylens Blocks
  "PIBLOCKLY_HW_HUSKYLENS_INIT_TITLE": "初始化 HuskyLens (I2C)",
  "PIBLOCKLY_HW_HUSKYLENS_INIT_TOOLTIP": "初始化 HuskyLens 感測器。必須放在 setup 中。需要安裝 DFRobot 的 'HUSKYLENS' 函式庫。",
  "PIBLOCKLY_HW_HUSKYLENS_SET_ALGORITHM_TITLE": "設定 HuskyLens 演算法為",
  "PIBLOCKLY_HW_HUSKYLENS_SET_ALGORITHM_TOOLTIP": "切換 HuskyLens 當前運行的演算法。",
  "PIBLOCKLY_HW_HUSKYLENS_ALGORITHM_FACE_RECOGNITION": "人臉辨識",
  "PIBLOCKLY_HW_HUSKYLENS_ALGORITHM_OBJECT_TRACKING": "物體追蹤",
  "PIBLOCKLY_HW_HUSKYLENS_ALGORITHM_OBJECT_RECOGNITION": "物體辨識",
  "PIBLOCKLY_HW_HUSKYLENS_ALGORITHM_LINE_TRACKING": "巡線",
  "PIBLOCKLY_HW_HUSKYLENS_ALGORITHM_COLOR_RECOGNITION": "顏色辨識",
  "PIBLOCKLY_HW_HUSKYLENS_ALGORITHM_TAG_RECOGNITION": "標籤辨識",
  "PIBLOCKLY_HW_HUSKYLENS_REQUEST_AND_CHECK_TITLE": "當 HuskyLens 偵測到結果時",
  "PIBLOCKLY_HW_HUSKYLENS_REQUEST_AND_CHECK_TOOLTIP": "向 HuskyLens 請求數據，並遍歷所有偵測到的結果。",
  "PIBLOCKLY_HW_HUSKYLENS_GET_RESULT_PROPERTY_TITLE": "取得",
  "PIBLOCKLY_HW_HUSKYLENS_GET_PROPERTY_OF_RESULT": "的當前結果",
  "PIBLOCKLY_HW_HUSKYLENS_GET_RESULT_PROPERTY_TOOLTIP": "在迴圈中取得當前結果的指定屬性。",
  "PIBLOCKLY_HW_HUSKYLENS_PROPERTY_X_CENTER": "X 中心點",
  "PIBLOCKLY_HW_HUSKYLENS_PROPERTY_Y_CENTER": "Y 中心點",
  "PIBLOCKLY_HW_HUSKYLENS_PROPERTY_WIDTH": "寬度",
  "PIBLOCKLY_HW_HUSKYLENS_PROPERTY_HEIGHT": "高度",
  "PIBLOCKLY_HW_HUSKYLENS_PROPERTY_ID": "ID",
};
